version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db-cv
    restart: always
    environment:
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: iwantmyjob
      POSTGRES_DB: CvData
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data